# Generated by Django 4.2.2 on 2023-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PUCCertificate',
            fields=[
                ('registration_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chasis_number', models.CharField(max_length=5)),
                ('certificate', models.FileField(upload_to='static/certificates')),
            ],
        ),
    ]
