# Generated by Django 4.2.2 on 2023-07-31 18:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puccertificate',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'enter a valid contact number')]),
        ),
        migrations.AddField(
            model_name='puccertificate',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
