# Generated by Django 4.2.2 on 2023-07-31 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0002_puccertificate_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccertificate',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'enter a valid contact number')]),
        ),
    ]
