# Generated by Django 4.2.2 on 2023-07-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0003_alter_puccertificate_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccertificate',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
