# Generated by Django 4.2.2 on 2023-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0004_alter_puccertificate_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puccertificate',
            name='date_uploaded',
        ),
    ]
