# Generated by Django 4.2.2 on 2023-08-01 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0005_remove_puccertificate_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='puccertificate',
            name='date_uploaded',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
