# Generated by Django 4.2.2 on 2023-08-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0007_alter_puccertificate_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccertificate',
            name='date_uploaded',
            field=models.DateField(),
        ),
    ]
