# Generated by Django 4.2.2 on 2023-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0008_alter_puccertificate_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccertificate',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
