# Generated by Django 4.2.2 on 2023-08-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0012_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
    ]
