# Generated by Django 4.2.2 on 2023-10-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucApp', '0013_alter_contactus_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccertificate',
            name='certificate',
            field=models.FileField(unique=True, upload_to='static/certificates'),
        ),
    ]
